export const games = [
	{
		id: 1,
		title: 'Cyberpunk 2077: Ultimate Edition',
		date: 'February 2024',
		price: '50,00',
		rating: 5,
		image: '/punk.jpg',
	},
	{
		id: 2,
		title: 'Tekken 8',
		date: 'July 2024',
		price: '55,00',
		rating: 4,
		image: '/tekken.jpg',
	},
	{
		id: 3,
		title: 'Last Epoch',
		date: 'December 2024',
		price: '45,00',
		rating: 5,
		image: '/epoch.jpg',
	},
	{
		id: 4,
		title: 'Elden Ring',
		date: 'June 2024',
		price: '35,00',
		rating: 3,
		image: '/elden.jpg',
	},
	{
		id: 5,
		title: 'Red Dead Redemption 2',
		date: 'January 2022',
		price: '29,00',
		rating: 4,
		image: '/rdr.jpg',
	},
	{
		id: 6,
		title: 'Grand Theft Auto V: Premium Online Edition',
		date: 'February 2024',
		price: '60,00',
		rating: 5,
		image: '/gta.jpg',
	},
];
