export const newsData = [
  {
    id: 1,
    title: "Title#1",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName1",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 2,
    title: "Title#2",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [],
  },
  {
    id: 3,
    title:
      "Following the delay of next Dragon Quest, producer Yu Miyake has reportedly been fired",
    text:
      "Halo Infinite fans are gonna have a good time with the newest patch, to be published on March 19.\n" +
      "In an article published on the franchise's official website, 343 has unveiled the additions included. Among these is an enhanced online experience, thanks to an overhaul of the network and servers used to host multiplayer matches. The Easy Anti-Cheat tool is also coming.\n" +
      "The game's stability has been improved overall, and there are new maps for Squad Battle mode (8v8) on the menu too.\n" +
      "Mark your calendars for March 19! 👀\n\nNext Tuesday, Halo Infinite will receive a networking overhaul, improved security, brand-new maps, and numerous community requested updates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie", "Activision Blizzard", "Coming Soon"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 4,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 5,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 6,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 7,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 8,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
  {
    id: 9,
    title: "Title",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet, blanditiis dolorem doloribus ducimus eius eum ipsum laboriosam minus necessitatibus, obcaecati pariatur rem similique soluta unde. Accusamus aspernatur at consectetur consequatur delectus dolorem ducimus inventore iure laboriosam minima molestias nemo nobis nulla numquam obcaecati, quam quisquam repellendus sunt ullam voluptates.",
    publicationDate: "05.04.2024",
    comments: 17,
    views: 439,
    img: "/gta.jpg",
    author: "userName2",
    tags: ["Action", "FPS", "Indie"],
    media: [
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/gta.jpg",
      "/punk.jpg",
      "/punk.jpg",
      "/elden.jpg",
    ],
    reactions: [
      { reaction: "CiFaceSmile", count: 3 },
      { reaction: "CiHeart", count: 4 },
    ],
  },
];
